[tool.poetry]
name = "genie-radio"
version = "0.1.0"
description = ""
authors = ["nir.godin <nir.godin@planckresolution.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
genie-datastores = { git = "https://github.com/nirgodin/genie-datastores.git", rev = "6065603f", extras = ["postgres", "redis"]}
spotipyio = {git = "https://github.com/nirgodin/spotipyio.git", rev = "5724c272"}
shazamio = ">=0.6.0,<0.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
